// <auto-generated />
using IntegrationHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrationHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HubDbContext))]
    [Migration("20260926175435_ComponentDefinitions")]
    partial class ComponentDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.ComponentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsArchived");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.ComponentVersionEntity", b =>
                {
                    b.Property<string>("ComponentId")
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComponentId", "Revision");

                    b.ToTable("ComponentVersions");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.DefinitionVersionEntity", b =>
                {
                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntegrationId", "Revision");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.DependencyEntity", b =>
                {
                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TargetIntegrationId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntegrationId", "TargetIntegrationId");

                    b.HasIndex("TargetIntegrationId");

                    b.ToTable("DependencyEntity");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.IntegrationEdgeEntity", b =>
                {
                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromNodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToNodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntegrationId", "Id");

                    b.ToTable("IntegrationEdgeEntity");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BusinessDomain")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DefinitionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OriginalDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("ValidationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarningCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Status", "BusinessDomain");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.IntegrationMessageEntity", b =>
                {
                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MessageName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicOrQueue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntegrationId", "MessageName");

                    b.HasIndex("MessageName");

                    b.ToTable("IntegrationMessages");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.IntegrationNodeEntity", b =>
                {
                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDestination")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSource")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SharedResourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SystemId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IntegrationId", "Id");

                    b.HasIndex("SharedResourceId");

                    b.HasIndex("SystemId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.MessageEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("Name");

                    b.ToTable("MessageEntity");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.RepositoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IntegrationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.ToTable("RepositoryEntity");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.RunbookEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IntegrationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.ToTable("RunbookEntity");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.SystemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BusinessDomain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.TagEntity", b =>
                {
                    b.Property<string>("IntegrationId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("IntegrationId", "Value");

                    b.ToTable("TagEntity");
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.ComponentVersionEntity", b =>
                {
                    b.HasOne("IntegrationHub.Infrastructure.Persistence.ComponentEntity", null)
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.DefinitionVersionEntity", b =>
                {
                    b.HasOne("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", null)
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.DependencyEntity", b =>
                {
                    b.HasOne("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", null)
                        .WithMany()
                        .HasForeignKey("TargetIntegrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.IntegrationEdgeEntity", b =>
                {
                    b.HasOne("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", null)
                        .WithMany("Edges")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.IntegrationMessageEntity", b =>
                {
                    b.HasOne("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", null)
                        .WithMany("Messages")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegrationHub.Infrastructure.Persistence.MessageEntity", null)
                        .WithMany()
                        .HasForeignKey("MessageName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.IntegrationNodeEntity", b =>
                {
                    b.HasOne("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", null)
                        .WithMany("Nodes")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntegrationHub.Infrastructure.Persistence.SystemEntity", null)
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.RepositoryEntity", b =>
                {
                    b.HasOne("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", null)
                        .WithMany("Repositories")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.RunbookEntity", b =>
                {
                    b.HasOne("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", null)
                        .WithMany("Runbooks")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.TagEntity", b =>
                {
                    b.HasOne("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IntegrationHub.Infrastructure.Persistence.IntegrationEntity", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Edges");

                    b.Navigation("Messages");

                    b.Navigation("Nodes");

                    b.Navigation("Repositories");

                    b.Navigation("Runbooks");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
